server:
  port: 80

spring:
  rabbitmq:
      host: rabbitmq
  application:
    name: zipkin

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://eureka}/eureka/